### ISSUE TITLE
Valid drill-file for 1.1 pcb issue

### ISSUE THREAD

**Issue by aaydev** [konkotgit/PLUS-2A-FDC-LIGHT#1]
Hi! This is a great project!
Could you please attach plus2afdd.drl (against plus2afdd-drl_map.ps) for v.1.1 gerber? It's a problem for JLCPCB now:

plus2afdd-Edge_Cuts.gbr(Board Outline Layer):Gerber file with a board outline
plus2afdd-F_Paste.gbr(null): Non-gerber274X/excellon formats
plus2afdd-drl_map.ps(null): Non-gerber274X/excellon formats

**Comment by konkotgit** [comment]
Fixed in plus2afdc_light_1_1a_gerber.zip
